import Head from 'next/head'
import Grid from '../components/Grid'

function Home({ data }) {
  return (
    <>
      <Head>
        <title>Pokedex App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <Grid items={data.results} />
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const res = await fetch(`https://pokeapi.co/api/v2/pokemon?limit=60`)
  const data = await res.json()

  return { props: { data } }
}

export default Home
